// PostHog Engineer Impact Dashboard — shared config
// All judgment calls live here, explicitly, so they're inspectable rather than buried in code.

const path = require('path')

const REPO_PATH = path.resolve(__dirname, '..', 'repo')
const REPO_OWNER = 'PostHog'
const REPO_NAME = 'posthog'
const DEFAULT_BRANCH = 'master' // verified via exploration — NOT "main"

// WINDOW_END is a hardcoded literal date, per spec (not "new Date()") so reruns are reproducible.
const WINDOW_END = new Date('2026-08-28T00:00:00Z')
const WINDOW_DAYS = 90
const WINDOW_START = new Date(WINDOW_END.getTime() - WINDOW_DAYS * 86400_000)
const OLDER_HALF_CUTOFF = new Date(WINDOW_END.getTime() - 45 * 86400_000) // commits before this get rework-checked
const REWORK_LOOKAHEAD_DAYS = 14

const ELIGIBILITY_FLOOR_PRS = 3

const WEIGHTS = {
  durability: 0.5,
  judgment: 0.3,
  breadth: 0.2,
}

// Directory weight table — hand-assigned from a 2-minute look at repo structure, per spec.
// Philosophy: core backend/ingestion/data-model = 3, docs/tests/fixtures/infra = 1, everything else default 2.
const DIRECTORY_WEIGHTS = {
  // core (3)
  posthog: 3,
  ee: 3,
  products: 3,
  rust: 3,
  nodejs: 3,
  // low (1)
  docs: 1,
  playwright: 1,
  terraform: 1,
  devenv: 1,
  docker: 1,
}
const DEFAULT_DIRECTORY_WEIGHT = 2 // frontend, common, livestream, funnel-udf, services, packages, cli, bin, tools, patches, proto, and anything unlisted

// Noise filter: conventional-commit `chore` type. Matches observed ~14.6% of commits in this repo,
// which lines up with the ~15% ground truth — deliberately not a keyword list.
const CHORE_NOISE_RE = /^chore(\([^)]*\))?!?:/i

// PR number embedded in squash-merge commit subjects, e.g. "fix(flags): ... (#87287)"
const PR_REF_RE = /\(#(\d+)\)\s*$/

// Bot detection. Every bot login actually observed in this repo's commit history ends in [bot] —
// this list is a defensive fallback for bare (non-[bot]) logins that may show up in Step 2's
// reviewer/author login data. Anything ambiguous should be flagged in reports, not silently decided.
const BOT_SUFFIX_RE = /\[bot\]$/i
const KNOWN_BOT_LOGINS = new Set([
  'dependabot',
  'renovate',
  'github-actions',
  'posthog-bot',
  'snyk-bot',
  'imgbot',
  'mendral-app',
])

function isBotLogin(login) {
  if (!login) return false
  const l = login.toLowerCase()
  return BOT_SUFFIX_RE.test(l) || KNOWN_BOT_LOGINS.has(l)
}

// Generated/data-artifact files: line deltas here aren't engineering signal (a codegen run or a
// lockfile bump can add/delete tens of thousands of lines mechanically). Excluded from the
// durability line count specifically — a small, explicit, hand-inspectable list in the same spirit
// as the directory weight table, not a heuristic buried in code.
const GENERATED_PATH_RE = /generated/i
const GENERATED_EXACT_PATHS = new Set([
  '.test_durations', // CI test-shard timing data, mechanically rewritten (confirmed outlier: PR #87687, ~200k added+deleted lines)
  'pnpm-lock.yaml',
  'package-lock.json',
  'yarn.lock',
  'poetry.lock',
  'uv.lock',
  'posthog/schema.py', // header: "DO NOT EDIT THIS FILE DIRECTLY" — generated from frontend/src/types.ts
  'posthog/schema_enums.py',
  'frontend/src/queries/schema.json',
  'frontend/src/queries/schema/schema-general.ts',
  'frontend/snapshots.yml', // test-snapshot manifest, mechanically updated by snapshot tooling
])

function isGeneratedOrDataFile(filePath) {
  return GENERATED_EXACT_PATHS.has(filePath) || GENERATED_PATH_RE.test(filePath)
}

function topLevelDir(filePath) {
  const idx = filePath.indexOf('/')
  return idx === -1 ? filePath : filePath.slice(0, idx)
}

function directoryWeight(filePath) {
  const dir = topLevelDir(filePath)
  return DIRECTORY_WEIGHTS[dir] ?? DEFAULT_DIRECTORY_WEIGHT
}

module.exports = {
  REPO_PATH,
  REPO_OWNER,
  REPO_NAME,
  DEFAULT_BRANCH,
  WINDOW_END,
  WINDOW_START,
  WINDOW_DAYS,
  OLDER_HALF_CUTOFF,
  REWORK_LOOKAHEAD_DAYS,
  ELIGIBILITY_FLOOR_PRS,
  WEIGHTS,
  DIRECTORY_WEIGHTS,
  DEFAULT_DIRECTORY_WEIGHT,
  CHORE_NOISE_RE,
  PR_REF_RE,
  BOT_SUFFIX_RE,
  KNOWN_BOT_LOGINS,
  isBotLogin,
  isGeneratedOrDataFile,
  GENERATED_EXACT_PATHS,
  topLevelDir,
  directoryWeight,
}
